version: "3.8"

x-common-env: &common-env
  restart: always
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    # - UMASK=${UMASK}
    - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    - VERSION=docker

volumes:
  portainer_data:

services:

  jellyfin:
    image: nyanmisaka/jellyfin:latest
    privileged: true
    <<: *common-env
    volumes:
      - ${CONFIGS}/jellyfin:/config
      - ${DOWNLOADS}:/downloads
      - ${MOVIES}:/movies
      - ${TV}:/tv
      - ${MUSIC}:/music
    ports:
      - 8096:8096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    <<: *common-env
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ${CONFIGS}/qbittorrent/:/config
      - ${DOWNLOADS}:/downloads

  # Feeds with torrents to radarr and sonarr
  jackett:
    image: linuxserver/jackett:latest
    <<: *common-env
    volumes:
      - ${CONFIGS}/jackett:/config
      - ${DOWNLOADS}/blackhole:/downloads
    ports:
      - 9117:9117

  # for automaticly having movies
  radarr:
    image: linuxserver/radarr:latest
    <<: *common-env
    volumes:
      - ${CONFIGS}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    links:
      - qbittorrent
      - jackett

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    <<: *common-env
    volumes:
      - ${CONFIGS}/sonarr:/config
      - ${TV}:/tv
      - ${DOWNLOADS}:/downloads
    links:
      - qbittorrent
      - jackett
    ports:
      - 8989:8989

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    <<: *common-env
    volumes:
      - ${CONFIGS}/bazarr:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
    ports:
      - 6767:6767
    links:
      - sonarr
      - radarr

